### PR TITLE
Migrate to smgl v0.11.0-rc.2's new registration schema

### PR DESCRIPTION
**Pull request by csparker247**
## Summary

- Updated `graph/src/graph.cpp` to use smgl's new node-registration API: migrated from `smgl::RegisterNode<...>()` template instantiation to `smgl::RegisterNodes(SMGL_NODE(...), ...)` across all three registration groups (Core, Meshing, and Texturing nodes), wrapping each node type in the `SMGL_NODE` macro and fully qualifying names with the `volcart::` namespace.
- Bumped smgl dependency from v0.10.1 (GitLab mirror) to v0.11.0-rc.2 by updating `cmake/Buildsmgl.cmake` to fetch from the official GitHub repository (`github.com/educelab/smgl.git`), as the stale GitLab mirror lacks the new `RegisterNodes` and `SMGL_NODE` APIs, and v0.11.0-rc.2 is only tagged on GitHub.
- This dependency upgrade fixes a compilation failure in CI, enabling the graph module to build with smgl's revised public registration interface.

### CODE REVIEW

**Comment by csparker247** [comment]
The Debian CI jobs are now passing, confirming the smgl v0.11.0-rc.2 fix (db8b3a25) resolves the actual build break.

The macOS jobs (`macOS (26, {14..15})`, `macOS (15, 14)`) are still failing, but with an unrelated, pre-existing error:

```
/opt/homebrew/include/vtk-9.6/vtkfmt/vtkfmt/chrono.h:340:7: error: use of undeclared identifier 'const_check'
```

This is a VTK/Homebrew `fmt` incompatibility in `vtkfmt`'s bundled headers, not something caused by this PR — the identical error occurs on the CI run from before the smgl fix was pushed. A local macOS build with the same Homebrew `fmt` (12.1.0) / `vtk` (9.6.2) versions completes successfully, so this looks specific to the GitHub-hosted macOS runner's environment rather than a real incompatibility. Tracking as a separate, unrelated CI issue.
